name: workflow-serasa-ci
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v1
        with:
          script: |
            git clone -b master "https://github.com/fgiordanelli/Serasa.git"
            cd Serasa
            sudo docker build -t myimage .
            sudo docker run -d --name mycontainer -p 80:80 myimage
          
